apiVersion: v1
kind: PersistentVolume
metadata:
  name: banco
  labels:
    type: banco
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /banco/

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: app
  labels:
    type: app
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /app/