apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
  - port: 3306
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30010
  selector:
    app: php